### ISSUE TITLE
Changing diff titles in zonal mean line plots?

### ISSUE THREAD

**Issue by kaabre** [ACME-Climate/acme_diags#134]
![image](https://user-images.githubusercontent.com/21698499/37433002-90aba91c-2797-11e8-8e85-bd329ccb7979.png)
 The difference title on the bottom plot in plots like these does not follow what I specify for the diff_title parameter.  Is there a way to specify this title to be something other than Test - Reference?

**Comment by zshaheen** [comment]
@kaabre The latest code on master fixes this issue. The image below is what the title is when there isn't a `diff_title` parameter defined.

![screen shot 2018-03-22 at 7 30 35 pm](https://user-images.githubusercontent.com/4239938/37808558-3cc520ae-2e08-11e8-803e-90b33b7e8185.png)

And we can change it now:
![screen shot 2018-03-22 at 7 32 07 pm](https://user-images.githubusercontent.com/4239938/37808579-57245636-2e08-11e8-9b8d-aef2cff608f6.png)

I guess one question to both you and @chengzhuzhang: should the 'Test: ' and 'Reference: ' be modifiable via the `test_title` and `reference_title` parameter respectively? Since right now, those values are hard-coded.

**Comment by chengzhuzhang** [comment]
@zshaheen  good point. I think  'Test: ' and 'Reference: ' shouldn't be hardcoded. And the users should be able to modify though test_title and reference _title

**Comment by kaabre** [comment]
Great!  Thank you!

**Comment by zshaheen** [comment]
As of 6f9e9ea79e08a01decdfb59d63f30ffcffafb71c, both 'Reference' and 'Test' can be changed by the `reference_title` and `test_title` parameter respectively.
