### ISSUE TITLE
Add new variables to ACME default lat-lon

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_diags#63]
I'd like to add new variables to the ACME default lat-lon plot sets:

- NetCF (CERES-EBAF TOA, surface)
- SHFLX, netSW surface, netLW surface, net flux sfc (ERA-Interim)
- LHFLX, SHFLX, netSW surface, netLW surface, net flux sfc (MERRA)
- Sea level pressure

**Comment by glpotter** [comment]
@golaz @chengzhuzhang , the new ERA-Interim  in /space1/test_data/acme_diags_observations contains hfls and hfss,(LHFLX, SHFLX)  rlus, rlds (netlw surface=rlds-rlus), rsds, rsus (net sw surf=rsds-rsus) and the net flux at the surface would be the difference between the LW and 
SW surface fluxes. It looks like the MERRA2 is missing hfss - I'll fix this. Otherwise MERRA2 has everything too.

**Comment by chengzhuzhang** [comment]
@golaz , I have implemented the new variables that are required in this issue with @glpotter 's newly processed Reanalysis data. 
I ran the lat-loa set, which is available here. 
http://aims4.llnl.gov:8000/zhang40/FC5COSP_new_var_reanalysis/

I have checked the plots. Would you also look at the new variables and see if there are abnormal plots? I have put the new reanalysis on acme1. Once you reviewed the results, I will copy the data to NERSC and merge the branch to master. Thanks. 

The equivalent run with old reanalysis are here (with less variables and slightly different years)
http://aims4.llnl.gov:8000/zhang40/v1.0.0-all-sets-vcs-10-19-2017-2/

**Comment by golaz** [comment]
@chengzhuzhang : the plots with the new variables look good. Thank you for adding them. I think you can close this issue now.

**Comment by chengzhuzhang** [comment]
Thank you @golaz 
I merged the pull request https://github.com/ACME-Climate/acme_diags/pull/112
And the new analysis are now available both on acme1 and edison
