### ISSUE TITLE
JSON syntax checker

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_diags#96]
JSON is rather unforgiving when it comes to its syntax. Would it be possible to implement a syntax checker that provides some useful feedback to the user? Right now, ACME Diags will fail with an obscure error message.

**Comment by zshaheen** [comment]
If I remember correctly, the error is that it can't parse the JSON/file or something like that.

In the documentation, we used to recommend that a user use [this](https://jsonlint.com/) website to check the syntax. However, since we're moving over to `.cfg` files, I don't think we should implement a built-in JSON validator. Eventually, all of the `.json` files will be `.cfg` files.

**Comment by chengzhuzhang** [comment]
Created an new issue: convert default json files to cfg files #97
